[book]
title = "An Intro to ROS 2 for Rover"
description = "A book about ROS 2 for the Sooner Rover Team."
authors = ["The Sooner Rover Team"]

language = "en"
multilingual = false
src = "src"
edition = "2021"
